### ISSUE TITLE
Create Insurgent Faction (OpFor)

### ISSUE THREAD

**Issue by JamesTheClarke** [JamesTheClarke/A3-Missions#6]
A playable OpFor faction has to be created which matches the aesthetic of the civilians present in the AO.

Special features:
- invisible backpacks (to store weapons and explosives)
- automatic deletion of any face wear (googles) upon spawn in order to mask better amongst AI civilians
- if possible: automatic reset of custom face texture to a random vanilla face in order to mask better amongst AI civilians

**Comment by JamesTheClarke** [comment]
I'm debating with myself if OpFor leaders should receive long-range radios or stick to 343 only. Meaning they have to come up with a plan at the beginning but then have little to no way of coordinating with themselves once the cells are split up and out of range.

@milivojm what do you think?

**Comment by milivojm** [comment]
I'd give them just short range radios to make it more true to being under-equipped insurgents than proper army. That will definitely give attackers some edge since defenders will lack adaptability.

But there is a problem. If we do that, we need to disable group and side channel. Because they will definitely try to cheat their way through it, or map. Disabling it, means no map markers unless global. To me, that is actually fine as I've always considered arma 3 map too unrealistic with all the perfectly shared information. But, you are more sensible and might not share my hardcore stance on that. :)

BTW, we can disable channels per player -> https://community.bistudio.com/wiki/enableChannel meaning BLUFOR can have all channels enabled, while OPFOR only global.
